spring:
  application:
    name: notes-service
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081