server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: notes-service
          uri: lb://NOTES-SERVICE
          predicates:
            - Path=/api/notes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/